-- MySQL Script generated by MySQL Workbench
-- Thu Nov 22 19:41:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inven
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inven
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `inven`.`kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kategori` (
  `id_kategori` VARCHAR(8) NOT NULL,
  `nama_kategori` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`simpan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpan` (
  `id_simpan` VARCHAR(8) NOT NULL,
  `nama_tmpsimpan` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_simpan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barang` (
  `id_barang` VARCHAR(8) NOT NULL,
  `nama_barang` VARCHAR(25) NULL DEFAULT NULL,
  `harga_barang` INT(11) NULL DEFAULT NULL,
  `stok_barang` INT(11) NULL DEFAULT NULL,
  `gambar_barang` TINYTEXT NULL DEFAULT NULL,
  `kategori_id_kategori` VARCHAR(8) NOT NULL,
  `simpan_id_simpan` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_barang`),
  INDEX `fk_barang_kategori_idx` (`kategori_id_kategori` ASC),
  INDEX `fk_barang_simpan1_idx` (`simpan_id_simpan` ASC),
  CONSTRAINT `fk_barang_kategori`
    FOREIGN KEY (`kategori_id_kategori`)
    REFERENCES `kategori` (`id_kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barang_simpan1`
    FOREIGN KEY (`simpan_id_simpan`)
    REFERENCES `simpan` (`id_simpan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(254) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`barang_keluar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barang_keluar` (
  `kode_keluar` VARCHAR(8) NOT NULL,
  `tgl_keluar` DATETIME NULL DEFAULT NULL,
  `keterangan_keluar` TINYTEXT NULL DEFAULT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`kode_keluar`),
  INDEX `fk_barang_keluar_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_barang_keluar_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supplier` (
  `id_supplier` VARCHAR(8) NOT NULL,
  `nama_supplier` VARCHAR(25) NULL DEFAULT NULL,
  `notelp_supplier` VARCHAR(13) NULL DEFAULT NULL,
  `alamat_supplier` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_supplier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`barang_masuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barang_masuk` (
  `kode_masuk` VARCHAR(8) NOT NULL,
  `tgl_masuk` DATETIME NULL DEFAULT NULL,
  `keterangan_masuk` TINYTEXT NULL DEFAULT NULL,
  `supplier_id_supplier` VARCHAR(8) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`kode_masuk`),
  INDEX `fk_barang_masuk_supplier1_idx` (`supplier_id_supplier` ASC),
  INDEX `fk_barang_masuk_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_barang_masuk_supplier1`
    FOREIGN KEY (`supplier_id_supplier`)
    REFERENCES `supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barang_masuk_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`barang_retur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barang_retur` (
  `kode_retur` VARCHAR(8) NOT NULL,
  `tgl_retur` DATETIME NULL DEFAULT NULL,
  `keterangan_retur` TINYTEXT NULL DEFAULT NULL,
  `supplier_id_supplier` VARCHAR(8) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`kode_retur`),
  INDEX `fk_barang_retur_supplier1_idx` (`supplier_id_supplier` ASC),
  INDEX `fk_barang_retur_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_barang_retur_supplier1`
    FOREIGN KEY (`supplier_id_supplier`)
    REFERENCES `supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barang_retur_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`detail_keluar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detail_keluar` (
  `iddetail_keluar` VARCHAR(8) NOT NULL,
  `stok_keluar` INT(11) NULL DEFAULT NULL,
  `barang_id_barang` VARCHAR(8) NOT NULL,
  `barang_keluar_kode_keluar` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`iddetail_keluar`),
  INDEX `fk_detail_keluar_barang1_idx` (`barang_id_barang` ASC),
  INDEX `fk_detail_keluar_barang_keluar1_idx` (`barang_keluar_kode_keluar` ASC),
  CONSTRAINT `fk_detail_keluar_barang1`
    FOREIGN KEY (`barang_id_barang`)
    REFERENCES `barang` (`id_barang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_keluar_barang_keluar1`
    FOREIGN KEY (`barang_keluar_kode_keluar`)
    REFERENCES `barang_keluar` (`kode_keluar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`detail_masuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detail_masuk` (
  `iddetail_masuk` VARCHAR(8) NOT NULL,
  `stok_masuk` INT(11) NULL DEFAULT NULL,
  `barang_id_barang` VARCHAR(8) NOT NULL,
  `barang_masuk_kode_masuk` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`iddetail_masuk`),
  INDEX `fk_detail_masuk_barang1_idx` (`barang_id_barang` ASC),
  INDEX `fk_detail_masuk_barang_masuk1_idx` (`barang_masuk_kode_masuk` ASC),
  CONSTRAINT `fk_detail_masuk_barang1`
    FOREIGN KEY (`barang_id_barang`)
    REFERENCES `barang` (`id_barang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_masuk_barang_masuk1`
    FOREIGN KEY (`barang_masuk_kode_masuk`)
    REFERENCES `barang_masuk` (`kode_masuk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`detail_retur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detail_retur` (
  `iddetail_retur` VARCHAR(8) NOT NULL,
  `stok_retur` INT(11) NULL DEFAULT NULL,
  `keterangan_barangretur` TINYTEXT NULL DEFAULT NULL,
  `barang_id_barang` VARCHAR(8) NOT NULL,
  `barang_retur_kode_retur` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`iddetail_retur`),
  INDEX `fk_detail_retur_barang1_idx` (`barang_id_barang` ASC),
  INDEX `fk_detail_retur_barang_retur1_idx` (`barang_retur_kode_retur` ASC),
  CONSTRAINT `fk_detail_retur_barang1`
    FOREIGN KEY (`barang_id_barang`)
    REFERENCES `barang` (`id_barang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_retur_barang_retur1`
    FOREIGN KEY (`barang_retur_kode_retur`)
    REFERENCES `barang_retur` (`kode_retur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inven`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_groups` (
  `id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_users_groups` (`user_id` ASC, `group_id` ASC),
  INDEX `fk_users_groups_users1_idx` (`user_id` ASC),
  INDEX `fk_users_groups_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Placeholder table for view `inven`.`barangmasuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barangmasuk` (`kode_masuk` INT, `tgl_masuk` INT, `keterangan_masuk` INT, `supplier_id_supplier` INT, `users_id` INT, `id` INT, `ip_address` INT, `username` INT, `password` INT, `salt` INT, `email` INT, `activation_code` INT, `forgotten_password_code` INT, `forgotten_password_time` INT, `remember_code` INT, `created_on` INT, `last_login` INT, `active` INT, `first_name` INT, `last_name` INT, `company` INT, `phone` INT, `id_supplier` INT, `nama_supplier` INT, `notelp_supplier` INT, `alamat_supplier` INT);

-- -----------------------------------------------------
-- Placeholder table for view `detailmasuk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detailmasuk` (`iddetail_masuk` INT, `stok_masuk` INT, `barang_id_barang` INT, `barang_masuk_kode_masuk` INT, `id_barang` INT, `nama_barang` INT, `harga_barang` INT, `stok_barang` INT, `gambar_barang` INT, `kategori_id_kategori` INT, `simpan_id_simpan` INT, `kode_masuk` INT, `tgl_masuk` INT, `keterangan_masuk` INT, `supplier_id_supplier` INT, `users_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `inven`.`namakategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namakategori` (`id_barang` INT, `nama_barang` INT, `harga_barang` INT, `stok_barang` INT, `gambar_barang` INT, `kategori_id_kategori` INT, `simpan_id_simpan` INT, `id_kategori` INT, `nama_kategori` INT, `id_simpan` INT, `nama_tmpsimpan` INT);

-- -----------------------------------------------------
-- View `inven`.`barangmasuk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barangmasuk`;

CREATE  OR REPLACE VIEW `barangmasuk`  AS  select `barang_masuk`.`kode_masuk` AS `kode_masuk`,`barang_masuk`.`tgl_masuk` AS `tgl_masuk`,`barang_masuk`.`keterangan_masuk` AS `keterangan_masuk`,`barang_masuk`.`supplier_id_supplier` AS `supplier_id_supplier`,`barang_masuk`.`users_id` AS `users_id`,`users`.`id` AS `id`,`users`.`ip_address` AS `ip_address`,`users`.`username` AS `username`,`users`.`password` AS `password`,`users`.`salt` AS `salt`,`users`.`email` AS `email`,`users`.`activation_code` AS `activation_code`,`users`.`forgotten_password_code` AS `forgotten_password_code`,`users`.`forgotten_password_time` AS `forgotten_password_time`,`users`.`remember_code` AS `remember_code`,`users`.`created_on` AS `created_on`,`users`.`last_login` AS `last_login`,`users`.`active` AS `active`,`users`.`first_name` AS `first_name`,`users`.`last_name` AS `last_name`,`users`.`company` AS `company`,`users`.`phone` AS `phone`,`supplier`.`id_supplier` AS `id_supplier`,`supplier`.`nama_supplier` AS `nama_supplier`,`supplier`.`notelp_supplier` AS `notelp_supplier`,`supplier`.`alamat_supplier` AS `alamat_supplier` from ((`barang_masuk` join `users`) join `supplier`) where ((`barang_masuk`.`users_id` = `users`.`id`) and (`barang_masuk`.`supplier_id_supplier` = `supplier`.`id_supplier`));

-- -----------------------------------------------------
-- View `inven`.`detailmasuk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detailmasuk`;
CREATE  OR REPLACE VIEW `detailmasuk`  AS  select `detail_masuk`.`iddetail_masuk` AS `iddetail_masuk`,`detail_masuk`.`stok_masuk` AS `stok_masuk`,`detail_masuk`.`barang_id_barang` AS `barang_id_barang`,`detail_masuk`.`barang_masuk_kode_masuk` AS `barang_masuk_kode_masuk`,`barang`.`id_barang` AS `id_barang`,`barang`.`nama_barang` AS `nama_barang`,`barang`.`harga_barang` AS `harga_barang`,`barang`.`stok_barang` AS `stok_barang`,`barang`.`gambar_barang` AS `gambar_barang`,`barang`.`kategori_id_kategori` AS `kategori_id_kategori`,`barang`.`simpan_id_simpan` AS `simpan_id_simpan`,`barang_masuk`.`kode_masuk` AS `kode_masuk`,`barang_masuk`.`tgl_masuk` AS `tgl_masuk`,`barang_masuk`.`keterangan_masuk` AS `keterangan_masuk`,`barang_masuk`.`supplier_id_supplier` AS `supplier_id_supplier`,`barang_masuk`.`users_id` AS `users_id` from ((`detail_masuk` join `barang`) join `barang_masuk`) where ((`detail_masuk`.`barang_id_barang` = `barang`.`id_barang`) and (`detail_masuk`.`barang_masuk_kode_masuk` = `barang_masuk`.`kode_masuk`));

-- -----------------------------------------------------
-- View `inven`.`namakategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `namakategori`;
CREATE  OR REPLACE VIEW `namakategori`  AS  select `barang`.`id_barang` AS `id_barang`,`barang`.`nama_barang` AS `nama_barang`,`barang`.`harga_barang` AS `harga_barang`,`barang`.`stok_barang` AS `stok_barang`,`barang`.`gambar_barang` AS `gambar_barang`,`barang`.`kategori_id_kategori` AS `kategori_id_kategori`,`barang`.`simpan_id_simpan` AS `simpan_id_simpan`,`kategori`.`id_kategori` AS `id_kategori`,`kategori`.`nama_kategori` AS `nama_kategori`,`simpan`.`id_simpan` AS `id_simpan`,`simpan`.`nama_tmpsimpan` AS `nama_tmpsimpan` from ((`barang` join `kategori`) join `simpan`) where ((`barang`.`kategori_id_kategori` = `kategori`.`id_kategori`) and (`barang`.`simpan_id_simpan` = `simpan`.`id_simpan`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
